name: Sewup CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: dependency (ubuntu)
      run: |
        sudo apt-get -q update
        sudo apt-get -qy install \
            curl build-essential make cmake libc6-dev \
            python3 python3-pip python3-pytest \
            python3-numpy python3-scipy python3-pandas python3-matplotlib \
            jupyter
        cd /usr/bin ; sudo ln -sf py.test-

    - name: make
      run: make
      
    - name: make test
      run: make test
      
    - name: make clean
      run: make clean
