name: Sewup CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: dependency
      run: |
        brew update
        brew install wget make cmake libccd python3
        
        python -m ensurepip --upgrade
        python get-pip.py
        
        pip install pytest numpy scipy pandas matplotlib pytest-faulthandler
        
        cd /usr/local/bin ; sudo ln -sf py.test-

    - name: make
      run: make
      
    - name: make test
      run: make test
      
    - name: make clean
      run: make clean
